### PR TITLE
Feature/user registrations

### PR DESCRIPTION
**Pull request by brayoh**
## Status
**READY**
## Migrations
YES 

## Description
This pull request will add the ability to allow users  to register while using postgres  for data persistence, migration script for migrating data when changes are made.

## Todos
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by JayKay24** [comment]
Great stuff! Great progress! Just a reminder to add module docstrings when you've completed the tasks.

**Comment by brayoh** [comment]
@JayKay24 Thanks I'll improve on the documentation for my code.

**Comment by nelmandela** [comment]
Great job.

**Comment by Thuku** [comment]
Nice. Clean code and well organized. Make a point to add comments to some parts of your code.

**Pull request merged**
